development:
  adapter: mysql2
  database: bookings_dev
  username: ruby
  password: password
  host: localhost

test:
  adapter: mysql2
  database: bookings_test
  username: ruby
  password: password
  host: localhost

production:
  adapter: mysql2
  database: bookings_production
  username: root
  password: []
  host: localhost
